/**
 * traffic — vehicles and pedestrians on the road network.
 *
 * Reads roads.api.laneGraph(), routes agents with A*, drives them with IDM car-following and
 * junction control (signal phases on big crossings, priority/FCFS elsewhere), and renders the
 * whole fleet from a handful of instanced draw calls with night lighting.
 *
 * Publishes: world.traffic = { api, vehicles (count), pedestrians (count), congestion, list }
 * and `segment.traffic` (0..1) per sim tick for the roads traffic info view.
 */
import { hashString } from '../../shared/random.js';
import { LaneNetwork } from './LaneNetwork.js';
import { TrafficSim } from './TrafficSim.js';
import { TrafficRenderer } from './Renderer.js';

export const name = 'traffic';

let ctxRef = null;
let net = null;
let sim = null;
let renderer = null;
let density = 1;
let maxVehicles = 400;
let maxPeds = 460;
let drawDistance = 900;
let enabled = true;
let acc = 0;
const offs = [];

export async function init(ctx) {
  ctxRef = ctx;
  const { engine, world, events } = ctx;
  const q = engine.quality || {};
  const densityScale = 0.55 + 0.45 * (q.density === undefined ? 1 : q.density);
  maxVehicles = Math.round(900 * Math.min(1.15, densityScale));
  maxPeds = Math.round(760 * Math.min(1.15, densityScale));
  drawDistance = Math.min(q.drawDistance || 900, 640);

  const rng = world.rng ? world.rng.fork(hashString('traffic')) : Math.random;
  net = new LaneNetwork(world);
  sim = new TrafficSim(net, world, rng);
  renderer = new TrafficRenderer(ctx, maxVehicles, maxPeds);

  world.traffic.api = {
    /** 0 = empty streets · 1 = normal · 2 = rush hour. */
    setDensity(f) { density = Math.max(0, Math.min(2, Number(f) || 0)); return density; },
    getDensity() { return density; },
    /** Add up to n vehicles right now, preferring lanes near the camera. */
    spawnBurst(n = 20) {
      if (!net.ready) return 0;
      const made = sim.spawn(Math.max(0, Math.min(maxVehicles, n | 0)), () => nearLane());
      publish();
      return made;
    },
    /** Live vehicle records for audio / debug: { id, x, y, z, vx, vz, speed, type }. */
    getVehicles() { return sim.vehicles; },
    getPedestrians() { return sim.peds; },
    setEnabled(on) { enabled = !!on; if (renderer) renderer.group.visible = enabled; },
    stats() {
      return {
        vehicles: sim.vehicles.length, pedestrians: sim.peds.length, target: sim.target,
        congestion: +sim.congestion.toFixed(3), avgSpeedRatio: +sim.avgSpeedRatio.toFixed(3),
        lanes: net.laneElems.length, elements: net.elements.length, junctions: net.nodes.size,
        signals: [...net.nodes.values()].filter((n) => n.signalized).length,
        laneKm: +(net.totalLength / 1000).toFixed(2), density,
      };
    },
  };
  world.traffic.vehicles = 0;
  world.traffic.pedestrians = 0;
  world.traffic.congestion = 0;
  world.traffic.list = sim.vehicles;

  offs.push(events.on('sim:tick', () => {
    if (!net.ready) return;
    sim.writeSegmentLoads();
    world.traffic.congestion = +sim.congestion.toFixed(3);
  }));
  offs.push(events.on('roads:changed', () => { acc = 1e9; }));
}

/** Pick a lane close to the camera (used by spawnBurst so a burst is actually visible). */
function nearLane() {
  const cam = ctxRef.camera;
  let best = -1, bestD = Infinity;
  for (let i = 0; i < 14; i++) {
    const li = net.randomLane(sim.rng());
    if (li < 0) continue;
    const el = net.elements[li];
    const d = Math.hypot(el.sx - cam.position.x, el.sz - cam.position.z);
    if (d < bestD) { bestD = d; best = li; }
  }
  return best;
}

function publish() {
  const world = ctxRef.world;
  world.traffic.vehicles = sim.vehicles.length;
  world.traffic.pedestrians = sim.peds.length;
}

function targetCounts() {
  const world = ctxRef.world;
  const eco = world.economy || {};
  const laneLen = net.totalLength;
  if (!(laneLen > 0)) return { v: 0, p: 0 };
  // Two independent estimates, and we take the larger of the two floors: a city can have more
  // traffic than its street length suggests (jams) but never more than the network can hold.
  //   byNetwork — one vehicle per 24 m of lane at saturation (≈ 42 veh/lane-km, a busy arterial)
  //   byCity    — commuters actually generated by the population and the jobs on the map
  const byNetwork = laneLen / 24;
  const pop = Number(eco.population) || 0;
  const jobs = Number(eco.jobs) || 0;
  const byCity = 70 + pop * 0.075 + jobs * 0.050;
  // rush hours: two commuting peaks, quiet nights
  const h = world.time ? world.time.hour : 12;
  const rush = 0.50 + 0.50 * Math.max(
    Math.exp(-Math.pow((h - 8.2) / 2.8, 2)),
    Math.max(Math.exp(-Math.pow((h - 17.6) / 3.6, 2)), Math.exp(-Math.pow((h - 12.5) / 3.4, 2)) * 0.85)
  );
  const night = h < 5.2 || h > 22.6 ? 0.42 : 1;
  let v = Math.min(byNetwork, Math.max(byCity, byNetwork * 0.92)) * density * rush * night;
  v = Math.max(0, Math.min(maxVehicles, Math.round(v)));
  const pedLen = net.pedTotal || 0;
  const byWalk = pedLen / 26;
  let p = Math.min(byWalk, Math.max(45 + pop * 0.085, byWalk * 0.80)) * density * (night * 0.7 + 0.3) * (0.55 + 0.45 * rush);
  p = Math.max(0, Math.min(maxPeds, Math.round(p)));
  return { v, p };
}

export function update(dt, elapsed) {
  if (!ctxRef || !net || !enabled) return;
  const { world, camera } = ctxRef;
  acc += dt;
  if (acc > 0.5) {
    acc = 0;
    if (net.rebuild()) { sim.onNetwork(); publish(); }
  }
  if (!net.ready) return;

  const t = targetCounts();
  sim.target = t.v;
  sim.pedTarget = t.p;
  const dv = t.v - sim.vehicles.length;
  if (dv > 0) sim.spawn(Math.min(26, dv));
  else if (dv < -3) sim.despawnFar(Math.min(6, -dv));
  const dp = t.p - sim.peds.length;
  if (dp > 0) sim.spawnPeds(Math.min(34, dp));
  else if (dp < -4) sim.peds.length = Math.max(0, sim.peds.length - Math.min(8, -dp));

  const step = world.time && world.time.paused ? 0 : Math.min(0.05, dt);
  sim.update(step, camera.position.x, camera.position.z);

  const env = world.env || {};
  const nightF = Number(env.nightFactor) || 0;
  const wet = Number(env.wetness || env.rain) || 0;
  const fog = Number(env.fogDensity) || 0;
  // Headlights must not depend on one number another module owns: derive them from the sun's own
  // elevation (and the clock as a backstop) as well as env.nightFactor, so a car at 21:00 has its
  // lights on whatever the environment module currently reports.
  const sd = env.sunDirection;
  const sunUpY = sd && typeof sd.y === 'number' ? -sd.y : null;      // +1 overhead, <=0 below horizon
  const bySun = sunUpY === null ? 0 : 1 - Math.max(0, Math.min(1, (sunUpY + 0.035) / 0.155));
  const h = world.time ? world.time.hour : 12;
  const byClock = h < 6.4 || h > 19.4 ? 1 : (h < 7.4 ? (7.4 - h) : (h > 18.4 ? (h - 18.4) : 0));
  const lightsOn = Math.max(0, Math.min(1, Math.max(
    nightF * 1.7 - 0.10, bySun, Math.min(1, byClock), wet * 0.55, fog > 0.004 ? 0.5 : 0,
  )));
  // Contact shadows are an occlusion term, so they lean away from the sun and ease off after dark
  // where street lighting is omnidirectional and there is no single key to occlude.
  const contact = 0.95 - 0.40 * nightF;
  renderer.sync(sim.vehicles, sim.peds, camera, {
    drawDistance, lightsOn, contact, sunDir: env.sunDirection || null,
  });

  publish();
}

export function dispose() {
  for (const off of offs) { try { off(); } catch (_) { /* ignore */ } }
  offs.length = 0;
  if (renderer) renderer.dispose();
  if (ctxRef && ctxRef.world && ctxRef.world.traffic) {
    ctxRef.world.traffic.api = null;
    ctxRef.world.traffic.vehicles = 0;
    ctxRef.world.traffic.pedestrians = 0;
    ctxRef.world.traffic.list = [];
  }
  net = null; sim = null; renderer = null; ctxRef = null;
}
